apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
  name: node1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: node1
        app: node1
    spec:
      containers:
        - name: envoy-node1
          image: envoyproxy/envoy:v1.14.1
          ports:
            - containerPort: 8545
          resources: {}
          volumeMounts:
            - mountPath: /etc/envoy
              name: envoy-besu-config

        - name: node1
          args:
            - --config-file=/var/lib/besu/config.toml
            - --network-id=8873625120
            - --bootnodes=enode://9683f07e51ed54f30a58332db6cdabc0f2413127961d2ca11bfa637a091a6f738c5f0f977d3cfbc0b603f7cf78b3b05f1c6d58d3f9b7d37d1b3198590e1d5ade@10.101.168.28:30000
          image: hyperledger/besu:1.4.5
          ports:
            - containerPort: 30000
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/node/private
              name: node1key
            - mountPath: /var/lib/besu
              name: besu-config
            # - mountPath: /var/lib/node/data
            #   name: node1-ledger
            - mountPath: /var/lib/node/data/static-nodes.json
              subPath: static-nodes.json
              name: static-nodes
      volumes:
        - name: node1key
          secret:
            secretName: node1key
        - name: besu-config
          configMap:
            name: besu-config
        - name: envoy-besu-config
          configMap:
            name: envoy-besu-config
        # - name: node1-ledger
        #   persistentVolumeClaim:
        #     claimName: node1-claim
        - name: static-nodes
          configMap:
            name: static-nodes
            # items:
            #   key: static-nodes.json
            #   path: static-nodes.json
      restartPolicy: Always

status: {}
